version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phonebook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: ["go", "run", "cmd/main.go"]
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:password@db/phonebook?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: